import type { Setting_QuestionDisplay } from '@/api/api-models'
import {
  QuestionDisplayAlign,
  QuestionDisplayImageLayout,
  QuestionDisplayShadow,
  QuestionDisplayTransition,
} from '@/api/api-models'

export type QuestionDisplayVisualPreset = Omit<Setting_QuestionDisplay, 'syncScroll'>

export const MARSHMALLOW_QUESTION_DISPLAY_PRESET: QuestionDisplayVisualPreset = {
  font: 'Microsoft YaHei',
  nameFont: 'Microsoft YaHei',
  fontSize: 28,
  fontWeight: 500,
  nameFontSize: 18,
  nameFontWeight: 700,
  fontColor: '2B2828',
  nameFontColor: 'C25B67',
  backgroundColor: 'FFF7F6',
  backgroundOpacity: 98,
  borderColor: 'F1B5AF',
  borderWidth: 2,
  borderRadius: 20,
  contentPadding: 28,
  lineHeight: 1.58,
  showUserName: true,
  showBrand: true,
  showImage: true,
  imageLayout: QuestionDisplayImageLayout.Contain,
  imageMaxHeight: 360,
  transition: QuestionDisplayTransition.Fade,
  shadow: QuestionDisplayShadow.Soft,
  align: QuestionDisplayAlign.Left,
}

export const QUESTION_DISPLAY_PRESETS: Array<{ name: string; value: QuestionDisplayVisualPreset }> = [
  { name: '棉花糖', value: MARSHMALLOW_QUESTION_DISPLAY_PRESET },
  {
    name: '极简内容',
    value: {
      font: 'sans-serif',
      nameFont: 'sans-serif',
      fontSize: 32,
      fontWeight: 600,
      nameFontSize: 18,
      nameFontWeight: 600,
      fontColor: 'FFFFFF',
      nameFontColor: 'FFFFFF',
      backgroundColor: '000000',
      backgroundOpacity: 0,
      borderColor: '000000',
      borderWidth: 0,
      borderRadius: 0,
      contentPadding: 0,
      lineHeight: 1.5,
      showUserName: false,
      showBrand: false,
      showImage: false,
      imageLayout: QuestionDisplayImageLayout.Contain,
      imageMaxHeight: 320,
      transition: QuestionDisplayTransition.None,
      shadow: QuestionDisplayShadow.None,
      align: QuestionDisplayAlign.Left,
    },
  },
  {
    name: '标准卡片',
    value: {
      font: 'sans-serif',
      nameFont: 'sans-serif',
      fontSize: 28,
      fontWeight: 500,
      nameFontSize: 18,
      nameFontWeight: 700,
      fontColor: '1F2937',
      nameFontColor: '2563EB',
      backgroundColor: 'FFFFFF',
      backgroundOpacity: 98,
      borderColor: 'D8DEE8',
      borderWidth: 1,
      borderRadius: 12,
      contentPadding: 24,
      lineHeight: 1.55,
      showUserName: true,
      showBrand: true,
      showImage: true,
      imageLayout: QuestionDisplayImageLayout.Contain,
      imageMaxHeight: 320,
      transition: QuestionDisplayTransition.Fade,
      shadow: QuestionDisplayShadow.Soft,
      align: QuestionDisplayAlign.Left,
    },
  },
  {
    name: '深色直播',
    value: {
      font: 'Noto Sans SC',
      nameFont: 'Noto Sans SC',
      fontSize: 34,
      fontWeight: 700,
      nameFontSize: 20,
      nameFontWeight: 800,
      fontColor: 'F7F7F5',
      nameFontColor: '7DD3FC',
      backgroundColor: '17191C',
      backgroundOpacity: 94,
      borderColor: '48515A',
      borderWidth: 2,
      borderRadius: 10,
      contentPadding: 28,
      lineHeight: 1.45,
      showUserName: true,
      showBrand: true,
      showImage: true,
      imageLayout: QuestionDisplayImageLayout.Grid,
      imageMaxHeight: 360,
      transition: QuestionDisplayTransition.Slide,
      shadow: QuestionDisplayShadow.Strong,
      align: QuestionDisplayAlign.Left,
    },
  },
]

export function createDefaultQuestionDisplaySetting(): Setting_QuestionDisplay {
  return { ...MARSHMALLOW_QUESTION_DISPLAY_PRESET, syncScroll: true }
}
