import type { Setting_QuestionDisplay } from '@/api/api-models'
import {
  QuestionDisplayAlign,
  QuestionDisplayImageLayout,
  QuestionDisplayShadow,
  QuestionDisplayTransition,
  QuestionDisplayVerticalAlign,
} from '@/api/api-models'

export type QuestionDisplayVisualPreset = Omit<Setting_QuestionDisplay, 'syncScroll'>

export const SYSTEM_CHINESE_FONT_OPTIONS = [
  { label: '系统黑体 (Sans-serif)', value: 'sans-serif' },
  { label: '微软雅黑 (Microsoft YaHei)', value: 'Microsoft YaHei' },
  { label: '思源黑体 (Source Han Sans)', value: 'Source Han Sans SC' },
  { label: '思源宋体 (Source Han Serif)', value: 'Source Han Serif SC' },
  { label: 'Noto Sans SC', value: 'Noto Sans SC' },
  { label: 'Noto Serif SC', value: 'Noto Serif SC' },
  { label: '楷体 / 仿宋 (Kaiti)', value: 'STKaiti, KaiTi, serif' },
  { label: '苹方 (PingFang SC)', value: 'PingFang SC, sans-serif' },
]

export const MARSHMALLOW_QUESTION_DISPLAY_PRESET: QuestionDisplayVisualPreset = {
  font: 'Microsoft YaHei',
  nameFont: 'Microsoft YaHei',
  fontSize: 28,
  fontWeight: 500,
  nameFontSize: 18,
  nameFontWeight: 700,
  fontColor: '2B2828',
  nameFontColor: 'C25B67',
  backgroundColor: 'FFF7F6',
  backgroundOpacity: 98,
  borderColor: 'F1B5AF',
  borderWidth: 2,
  borderRadius: 20,
  contentPadding: 28,
  lineHeight: 1.58,
  letterSpacing: 0,
  nameLetterSpacing: 0,
  contentMaxWidth: 34,
  showUserName: true,
  showBrand: true,
  showImage: true,
  imageLayout: QuestionDisplayImageLayout.Contain,
  imageMaxHeight: 360,
  transition: QuestionDisplayTransition.Fade,
  shadow: QuestionDisplayShadow.Soft,
  textShadow: QuestionDisplayShadow.None,
  align: QuestionDisplayAlign.Left,
  verticalAlign: QuestionDisplayVerticalAlign.Top,
}

export const QUESTION_DISPLAY_PRESETS: Array<{ name: string; description: string; value: QuestionDisplayVisualPreset }> = [
  {
    name: '棉花糖',
    description: '粉白温和卡片，适合日常杂谈与棉花糖回信',
    value: MARSHMALLOW_QUESTION_DISPLAY_PRESET,
  },
  {
    name: '透明字幕',
    description: '无背景半透明白字带阴影，适合叠加在游戏/视频画面上',
    value: {
      font: 'sans-serif',
      nameFont: 'sans-serif',
      fontSize: 32,
      fontWeight: 600,
      nameFontSize: 18,
      nameFontWeight: 600,
      fontColor: 'FFFFFF',
      nameFontColor: 'E0E7FF',
      backgroundColor: '000000',
      backgroundOpacity: 0,
      borderColor: '000000',
      borderWidth: 0,
      borderRadius: 0,
      contentPadding: 16,
      lineHeight: 1.5,
      letterSpacing: 0.01,
      nameLetterSpacing: 0.02,
      contentMaxWidth: 0,
      showUserName: true,
      showBrand: false,
      showImage: true,
      imageLayout: QuestionDisplayImageLayout.Contain,
      imageMaxHeight: 320,
      transition: QuestionDisplayTransition.Fade,
      shadow: QuestionDisplayShadow.None,
      textShadow: QuestionDisplayShadow.Strong,
      align: QuestionDisplayAlign.Left,
      verticalAlign: QuestionDisplayVerticalAlign.Center,
    },
  },
  {
    name: '标准简约',
    description: '明亮干净现代卡片，通用性强',
    value: {
      font: 'sans-serif',
      nameFont: 'sans-serif',
      fontSize: 28,
      fontWeight: 500,
      nameFontSize: 18,
      nameFontWeight: 700,
      fontColor: '1F2937',
      nameFontColor: '2563EB',
      backgroundColor: 'FFFFFF',
      backgroundOpacity: 98,
      borderColor: 'E2E8F0',
      borderWidth: 1,
      borderRadius: 14,
      contentPadding: 24,
      lineHeight: 1.55,
      letterSpacing: 0,
      nameLetterSpacing: 0,
      contentMaxWidth: 34,
      showUserName: true,
      showBrand: true,
      showImage: true,
      imageLayout: QuestionDisplayImageLayout.Contain,
      imageMaxHeight: 320,
      transition: QuestionDisplayTransition.Fade,
      shadow: QuestionDisplayShadow.Soft,
      textShadow: QuestionDisplayShadow.None,
      align: QuestionDisplayAlign.Left,
      verticalAlign: QuestionDisplayVerticalAlign.Top,
    },
  },
  {
    name: '深色沉浸',
    description: '暗色高对比度卡片，夜间直播与暗色场景友好',
    value: {
      font: 'Noto Sans SC',
      nameFont: 'Noto Sans SC',
      fontSize: 32,
      fontWeight: 600,
      nameFontSize: 18,
      nameFontWeight: 700,
      fontColor: 'F8FAFC',
      nameFontColor: '38BDF8',
      backgroundColor: '0F172A',
      backgroundOpacity: 92,
      borderColor: '334155',
      borderWidth: 1,
      borderRadius: 16,
      contentPadding: 26,
      lineHeight: 1.5,
      letterSpacing: 0.01,
      nameLetterSpacing: 0.02,
      contentMaxWidth: 32,
      showUserName: true,
      showBrand: true,
      showImage: true,
      imageLayout: QuestionDisplayImageLayout.Grid,
      imageMaxHeight: 340,
      transition: QuestionDisplayTransition.Slide,
      shadow: QuestionDisplayShadow.Strong,
      textShadow: QuestionDisplayShadow.Soft,
      align: QuestionDisplayAlign.Left,
      verticalAlign: QuestionDisplayVerticalAlign.Top,
    },
  },
]

export function createDefaultQuestionDisplaySetting(): Setting_QuestionDisplay {
  return { ...MARSHMALLOW_QUESTION_DISPLAY_PRESET, syncScroll: true }
}
