/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressDisplay: typeof import('./components/manage/AddressDisplay.vue')['default']
    DanmakuContainer: typeof import('./components/DanmakuContainer.vue')['default']
    DanmakuItem: typeof import('./components/DanmakuItem.vue')['default']
    DynamicForm: typeof import('./components/DynamicForm.vue')['default']
    EventFetcherAlert: typeof import('./components/EventFetcherAlert.vue')['default']
    EventFetcherStatusCard: typeof import('./components/EventFetcherStatusCard.vue')['default']
    FeedbackItem: typeof import('./components/FeedbackItem.vue')['default']
    LiveInfoContainer: typeof import('./components/LiveInfoContainer.vue')['default']
    MonacoEditorComponent: typeof import('./components/MonacoEditorComponent.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NTag: typeof import('naive-ui')['NTag']
    PointGoodsItem: typeof import('./components/manage/PointGoodsItem.vue')['default']
    PointHistoryCard: typeof import('./components/manage/PointHistoryCard.vue')['default']
    PointOrderCard: typeof import('./components/manage/PointOrderCard.vue')['default']
    QuestionItem: typeof import('./components/QuestionItem.vue')['default']
    QuestionItems: typeof import('./components/QuestionItems.vue')['default']
    RegisterAndLogin: typeof import('./components/RegisterAndLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveCompoent: typeof import('./components/SaveCompoent.vue')['default']
    ScheduleList: typeof import('./components/ScheduleList.vue')['default']
    SimpleVideoCard: typeof import('./components/SimpleVideoCard.vue')['default']
    SimpleVirtualList: typeof import('./components/SimpleVirtualList.vue')['default']
    SongList: typeof import('./components/SongList.vue')['default']
    SongPlayer: typeof import('./components/SongPlayer.vue')['default']
    TempComponent: typeof import('./components/TempComponent.vue')['default']
    TurnstileVerify: typeof import('./components/TurnstileVerify.vue')['default']
    UserBasicInfoCard: typeof import('./components/UserBasicInfoCard.vue')['default']
    VEditor: typeof import('./components/VEditor.vue')['default']
    VideoCollectInfoCard: typeof import('./components/VideoCollectInfoCard.vue')['default']
  }
}
