/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressDisplay: typeof import('./components/manage/AddressDisplay.vue')['default']
    DanmakuContainer: typeof import('./components/DanmakuContainer.vue')['default']
    DanmakuItem: typeof import('./components/DanmakuItem.vue')['default']
    DynamicForm: typeof import('./components/DynamicForm.vue')['default']
    EventFetcherAlert: typeof import('./components/EventFetcherAlert.vue')['default']
    EventFetcherStatusCard: typeof import('./components/EventFetcherStatusCard.vue')['default']
    FeedbackItem: typeof import('./components/FeedbackItem.vue')['default']
    LiveInfoContainer: typeof import('./components/LiveInfoContainer.vue')['default']
    MonacoEditorComponent: typeof import('./components/MonacoEditorComponent.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NFlex: typeof import('naive-ui')['NFlex']
    NFormItemG: typeof import('naive-ui')['NFormItemG']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH4: typeof import('naive-ui')['NH4']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTab: typeof import('naive-ui')['NTab']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PointGoodsItem: typeof import('./components/manage/PointGoodsItem.vue')['default']
    PointHistoryCard: typeof import('./components/manage/PointHistoryCard.vue')['default']
    PointOrderCard: typeof import('./components/manage/PointOrderCard.vue')['default']
    QuestionItem: typeof import('./components/QuestionItem.vue')['default']
    QuestionItems: typeof import('./components/QuestionItems.vue')['default']
    RegisterAndLogin: typeof import('./components/RegisterAndLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveCompoent: typeof import('./components/SaveCompoent.vue')['default']
    ScheduleList: typeof import('./components/ScheduleList.vue')['default']
    SimpleVideoCard: typeof import('./components/SimpleVideoCard.vue')['default']
    SimpleVirtualList: typeof import('./components/SimpleVirtualList.vue')['default']
    SongList: typeof import('./components/SongList.vue')['default']
    SongPlayer: typeof import('./components/SongPlayer.vue')['default']
    TempComponent: typeof import('./components/TempComponent.vue')['default']
    TurnstileVerify: typeof import('./components/TurnstileVerify.vue')['default']
    UserBasicInfoCard: typeof import('./components/UserBasicInfoCard.vue')['default']
    VEditor: typeof import('./components/VEditor.vue')['default']
    VideoCollectInfoCard: typeof import('./components/VideoCollectInfoCard.vue')['default']
  }
}
